{% set name = "ilastik-napari" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ilastik-napari-{{ version }}.tar.gz
  sha256: b5ae109340fb20f247ef3350668b6da536d57356d2c0e371e895cfeec0ed90f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - napari
    - numpy >=1.20
    - python >={{ python_min }}
    - qtpy
    - scikit-learn
    - sparse

test:
  imports:
    - ilastik
    - ilastik.napari
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ilastik/ilastik-napari
  summary: ilastik plugin for napari
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
